package main

import (
	"testing"

	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"golang.org/x/crypto/bcrypt"
)

// Feature: university-bus-tracker, Property 2: Password Hashing Verification
// Validates: Requirements 3.4
// For any password string, the bcrypt hash generated by the Auth Service
// SHALL be verifiable against the original password using bcrypt's verification function,
// and SHALL NOT be verifiable against any other password string.
func TestProperty_PasswordHashingVerification(t *testing.T) {
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 1000

	properties := gopter.NewProperties(parameters)

	// Generator for passwords (8-100 chars as per design)
	passwordGen := gen.RegexMatch("[a-zA-Z0-9!@#$%^&*()_+=-]{8,100}")

	properties.Property("Hashed password verifies against original", prop.ForAll(
		func(password string) bool {
			// Hash the password
			hash, err := HashPassword(password, bcrypt.DefaultCost)
			if err != nil {
				t.Logf("Failed to hash password: %v", err)
				return false
			}

			// Verify the password matches the hash
			err = VerifyPassword(hash, password)
			if err != nil {
				t.Logf("Failed to verify correct password: %v", err)
				return false
			}

			return true
		},
		passwordGen,
	))

	properties.Property("Hashed password does not verify against different password", prop.ForAll(
		func(password1, password2 string) bool {
			// Only test when passwords are different
			if password1 == password2 {
				return true // Skip this case
			}

			// Hash the first password
			hash, err := HashPassword(password1, bcrypt.DefaultCost)
			if err != nil {
				t.Logf("Failed to hash password: %v", err)
				return false
			}

			// Verify the second password should NOT match the hash
			err = VerifyPassword(hash, password2)
			if err == nil {
				t.Logf("Different password incorrectly verified against hash")
				return false
			}

			return true
		},
		passwordGen,
		passwordGen,
	))

	properties.Property("Hash is always different for same password", prop.ForAll(
		func(password string) bool {
			// Hash the same password twice
			hash1, err := HashPassword(password, bcrypt.DefaultCost)
			if err != nil {
				return false
			}

			hash2, err := HashPassword(password, bcrypt.DefaultCost)
			if err != nil {
				return false
			}

			// Hashes should be different (bcrypt uses random salt)
			if hash1 == hash2 {
				t.Logf("Same password produced identical hashes (salt not random)")
				return false
			}

			// But both should verify against the original password
			if err := VerifyPassword(hash1, password); err != nil {
				return false
			}
			if err := VerifyPassword(hash2, password); err != nil {
				return false
			}

			return true
		},
		passwordGen,
	))

	properties.Property("Empty password fails", prop.ForAll(
		func() bool {
			// Hash empty password should work (bcrypt allows it)
			hash, err := HashPassword("", bcrypt.DefaultCost)
			if err != nil {
				return false
			}

			// Verify empty password against hash
			err = VerifyPassword(hash, "")
			return err == nil
		},
	))

	properties.TestingRun(t)
}

// Feature: university-bus-tracker, Property 2 (Cost variation)
// Test that different bcrypt costs produce valid hashes
func TestProperty_PasswordHashingWithDifferentCosts(t *testing.T) {
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 50

	properties := gopter.NewProperties(parameters)

	passwordGen := gen.RegexMatch("[a-zA-Z0-9!@#$%^&*()_+=-]{8,50}")
	// Cost range 4-14 (12 is default, higher is slower)
	costGen := gen.IntRange(4, 14)

	properties.Property("Hash with any valid cost verifies correctly", prop.ForAll(
		func(password string, cost int) bool {
			// Hash the password with specified cost
			hash, err := HashPassword(password, cost)
			if err != nil {
				t.Logf("Failed to hash password with cost %d: %v", cost, err)
				return false
			}

			// Verify the password
			err = VerifyPassword(hash, password)
			if err != nil {
				t.Logf("Failed to verify password hashed with cost %d: %v", cost, err)
				return false
			}

			return true
		},
		passwordGen,
		costGen,
	))

	properties.TestingRun(t)
}
